language: rust
rust: stable
dist: xenial
jobs:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
before_script:
  - rustc -V
  - cargo -V
  - git --version
  - echo $TRAVIS_BRANCH
  - git rev-parse HEAD
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy:
  - export PKG_CONFIG_ALLOW_CROSS=1
  - cargo build --target $TARGET --release
  - mkdir "gtrans-${TRAVIS_TAG}-${TARGET}"
  - cp target/$TARGET/release/gtrans LICENSE README.md "gtrans-${TRAVIS_TAG}-${TARGET}"
  - zip "gtrans-${TRAVIS_TAG}-${TARGET}.zip" -r "gtrans-${TRAVIS_TAG}-${TARGET}"
deploy:
  provider: releases
  token:
    secure: yRpO6s67NIaFHXKE2Gahv2caY1xDAo9WButKcqJk095sRwYC1b2JAZp5DKeYVrCGyE+Xdhnvd+Hak4H+ExMW8ILlSgGZi/77j2zLJD6yoSoHyQhGgVY1T0M7Xg5ow76p3wh3GDYE5H4zycWmqUTG8kV05MZXliUWFFpM1gIymCPi2WaxvOcXe47x2iizVE7DHKo82zwf3ybLFj+A+ObxYLuEo5qNzyf4IIqw8lHJtT2FZZSwhECrPjMU5lHCX/NQxulF463y/akiYuVM1jBnqL1dwOKmQIPwMfVzhQ5v4pJFROKHWoqcEwC0mRZQXEg/cjXPJEHUjQtlOCasci4qgEvIsL4luZsS76kjvQMplqku4dslIAuTHQplox5so75RzO5HBARGFrTYj3s37ZiNvsYh4LBn5qFfy6zKL/4h5U1+DenQoK492XjewK9DU3UXhzqgstklqYQa65Q7WRJzbwL2jEHb9ebcAjna/WxJ5YTct3Lr/S5178V9/djI+T74XrPr0w++uv6meOsQqpnxs1IrLkASKRnjUnWnsotKEvWGrlMKzULuxE3TxxcEnbV1Dh6atbKfEwleJAVvR1gbiqSbKpuagr6txgc6YnA/DORFN9W9juXv0DQqtNULjsNwaWbM73KCOoXQUchdNOzOnZufr42TOK3RQ2uvSec485c=
  file: gtrans-${TRAVIS_TAG}-${TARGET}.zip
  on:
    repo: ksk001100/gtrans
    tags: true
cache: cargo
